### ISSUE TITLE
Write a function that converts a Python dict (in a string) to a Julia Dict

### ISSUE THREAD

**Issue by juliohm** [michiboo/CDSAPI.jl#6]
It is nice that we have the functionality working with Julia dicts. Nice work.

I wonder if we could also have a function that takes a multi-line string as given by the website:

```julia
str = """
{
"variable": "all",
"product_type": "elevation_change",
"file_version": "20170405",
"format": "tgz"
}
"""
```
and converts it to a Julia dict:

```julia
Dict(
  "variable" => "all",
  "product_type" => "elevation_change",
  "file_version" => "20170405",
  "format" => "tgz"
)
```

**Comment by juliohm** [comment]
Thank you @michiboo for fixing the issue. Could you please rename the function to `py2ju` and remove the `println` statement?

At the end, the following Python call:

```python
c = cdsapi.Client()
c.retrieve("insitu-glaciers-elevation-mass",
{
"variable": "all",
"product_type": "elevation_change",
"file_version": "20170405",
"format": "tgz"
},
"download.tar.gz")
````

could be easily converted into a Julia call as:

```julia
using CDSAPI

CDSAPI.retrieve("insitu-glaciers-elevation-mass",
py2ju("""
{
"variable": "all",
"product_type": "elevation_change",
"file_version": "20170405",
"format": "tgz"
}
"""),
"download.tar.gz"))
```

Please let me know if you have other ideas. For the above code to work we need to export the `py2ju` function from the module.

**Comment by juliohm** [comment]
I've noticed that you have the function in place. I believe that the regular expressions are too complicated though. Could you try implement the following pseudo-code instead?

Given a string:

```python
{
"variable": "all",
"product_type": "elevation_change",
"file_version": "20170405",
"format": "tgz"
}
```

all we need to do is:

1. Remove the first and last words (i.e. "{" and "}")
2. Split resulting string by comma `split(str, ',')`
3. Loop over the list and split by colon `key, val = split(s, ':')`
4. Push a new pair `strip(key) => strip(val)` to the resulting dict

**Comment by LakshyaKhatri** [comment]
Will it be okay to iterate over the string line by line and if the line is a valid key-value pair then add it to dict?
cc: @juliohm

**Comment by michiboo** [comment]
I think it will not work as some input could have new line and some don't,
so IMO better to split the whole string input by comma

**Comment by LakshyaKhatri** [comment]
One more suggestion is: If this is all about JSON parsing we can also use the JSON.jl module.

**Comment by juliohm** [comment]
Nice suggestion @LakshyaKhatri , thanks for the PR as well.

**Comment by juliohm** [comment]
I wonder if we should just export `parse` from JSON? That is effectively what your PR is doing right?

What do you @michiboo of merging the PR and then removing the `py2ju` in favor of `JSON.parse`? You can simply do the following in your module:

```julia
using JSON: parse

export parse
```

I would also remove the `export retrieve` to force users to be explicit with `CDSAPI.retrieve`.
