### ISSUE TITLE
Remove indentation at beginning of line

### ISSUE THREAD

**Issue by juliohm** [michiboo/CDSAPI.jl#8]
It is not common practice to indent the lines after a `module` begin in Julia (lot of whitespace). Could you please remove the indentation for all lines so that they start at line beginnings?

**Comment by michiboo** [comment]
@juliohm  even for lines within loops and function?

**Comment by juliohm** [comment]
Just the first indentation level. The indentation of functions and loops
are great, please keep them 🙏
